import { Enchantment, ItemCategory } from "./types";

const ALL_CATEGORIES = [
  ItemCategory.SWORD,
  ItemCategory.AXE,
  ItemCategory.PICKAXE,
  ItemCategory.SHOVEL,
  ItemCategory.HOE,
  ItemCategory.HELMET,
  ItemCategory.CHESTPLATE,
  ItemCategory.LEGGINGS,
  ItemCategory.BOOTS,
  ItemCategory.BOW,
  ItemCategory.CROSSBOW,
  ItemCategory.TRIDENT,
  ItemCategory.FISHING_ROD,
  ItemCategory.MACE,
  ItemCategory.ELYTRA,
  ItemCategory.BOOK,
];

const ARMOR = [
  ItemCategory.HELMET,
  ItemCategory.CHESTPLATE,
  ItemCategory.LEGGINGS,
  ItemCategory.BOOTS,
];

export const ENCHANTMENTS: Enchantment[] = [
  {
    id: "protection",
    name: "Protection",
    maxLevel: 4,
    itemMultiplier: 1,
    bookMultiplier: 1,
    categories: [...ARMOR, ItemCategory.BOOK],
    conflicts: ["fire_protection", "blast_protection", "projectile_protection"],
  },
  {
    id: "fire_protection",
    name: "Fire Protection",
    maxLevel: 4,
    itemMultiplier: 2,
    bookMultiplier: 1,
    categories: [...ARMOR, ItemCategory.BOOK],
    conflicts: ["protection", "blast_protection", "projectile_protection"],
  },
  {
    id: "blast_protection",
    name: "Blast Protection",
    maxLevel: 4,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: [...ARMOR, ItemCategory.BOOK],
    conflicts: ["protection", "fire_protection", "projectile_protection"],
  },
  {
    id: "projectile_protection",
    name: "Projectile Protection",
    maxLevel: 4,
    itemMultiplier: 2,
    bookMultiplier: 1,
    categories: [...ARMOR, ItemCategory.BOOK],
    conflicts: ["protection", "fire_protection", "blast_protection"],
  },
  {
    id: "thorns",
    name: "Thorns",
    maxLevel: 3,
    itemMultiplier: 8,
    bookMultiplier: 4,
    categories: [...ARMOR, ItemCategory.BOOK],
    conflicts: [],
  },
  {
    id: "unbreaking",
    name: "Unbreaking",
    maxLevel: 3,
    itemMultiplier: 2,
    bookMultiplier: 1,
    categories: ALL_CATEGORIES,
    conflicts: [],
  },
  {
    id: "mending",
    name: "Mending",
    maxLevel: 1,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: ALL_CATEGORIES,
    conflicts: ["infinity"], // Specifically for bows
  },
  {
    id: "aqua_affinity",
    name: "Aqua Affinity",
    maxLevel: 1,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: [ItemCategory.HELMET, ItemCategory.BOOK],
    conflicts: [],
  },
  {
    id: "respiration",
    name: "Respiration",
    maxLevel: 3,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: [ItemCategory.HELMET, ItemCategory.BOOK],
    conflicts: [],
  },
  {
    id: "feather_falling",
    name: "Feather Falling",
    maxLevel: 4,
    itemMultiplier: 2,
    bookMultiplier: 1,
    categories: [ItemCategory.BOOTS, ItemCategory.BOOK],
    conflicts: [],
  },
  {
    id: "depth_strider",
    name: "Depth Strider",
    maxLevel: 3,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: [ItemCategory.BOOTS, ItemCategory.BOOK],
    conflicts: ["frost_walker"],
  },
  {
    id: "frost_walker",
    name: "Frost Walker",
    maxLevel: 2,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: [ItemCategory.BOOTS, ItemCategory.BOOK],
    conflicts: ["depth_strider"],
  },
  {
    id: "soul_speed",
    name: "Soul Speed",
    maxLevel: 3,
    itemMultiplier: 8,
    bookMultiplier: 4,
    categories: [ItemCategory.BOOTS, ItemCategory.BOOK],
    conflicts: [],
  },
  {
    id: "swift_sneak",
    name: "Swift Sneak",
    maxLevel: 3,
    itemMultiplier: 8,
    bookMultiplier: 4,
    categories: [ItemCategory.LEGGINGS, ItemCategory.BOOK],
    conflicts: [],
  },
  {
    id: "sharpness",
    name: "Sharpness",
    maxLevel: 5,
    itemMultiplier: 1,
    bookMultiplier: 1,
    categories: [ItemCategory.SWORD, ItemCategory.AXE, ItemCategory.BOOK],
    conflicts: ["smite", "bane_of_arthropods", "density", "breach"],
  },
  {
    id: "smite",
    name: "Smite",
    maxLevel: 5,
    itemMultiplier: 2,
    bookMultiplier: 1,
    categories: [ItemCategory.SWORD, ItemCategory.AXE, ItemCategory.MACE, ItemCategory.BOOK],
    conflicts: ["sharpness", "bane_of_arthropods", "density", "breach"],
  },
  {
    id: "bane_of_arthropods",
    name: "Bane of Arthropods",
    maxLevel: 5,
    itemMultiplier: 2,
    bookMultiplier: 1,
    categories: [ItemCategory.SWORD, ItemCategory.AXE, ItemCategory.MACE, ItemCategory.BOOK],
    conflicts: ["sharpness", "smite", "density", "breach"],
  },
  {
    id: "knockback",
    name: "Knockback",
    maxLevel: 2,
    itemMultiplier: 2,
    bookMultiplier: 1,
    categories: [ItemCategory.SWORD, ItemCategory.BOOK],
    conflicts: [],
  },
  {
    id: "fire_aspect",
    name: "Fire Aspect",
    maxLevel: 2,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: [ItemCategory.SWORD, ItemCategory.MACE, ItemCategory.BOOK],
    conflicts: [],
  },
  {
    id: "looting",
    name: "Looting",
    maxLevel: 3,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: [ItemCategory.SWORD, ItemCategory.BOOK],
    conflicts: [],
  },
  {
    id: "sweeping_edge",
    name: "Sweeping Edge",
    maxLevel: 3,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: [ItemCategory.SWORD, ItemCategory.BOOK],
    conflicts: [],
  },
  {
    id: "efficiency",
    name: "Efficiency",
    maxLevel: 5,
    itemMultiplier: 1,
    bookMultiplier: 1,
    categories: [ItemCategory.PICKAXE, ItemCategory.AXE, ItemCategory.SHOVEL, ItemCategory.HOE, ItemCategory.BOOK],
    conflicts: [],
  },
  {
    id: "silk_touch",
    name: "Silk Touch",
    maxLevel: 1,
    itemMultiplier: 8,
    bookMultiplier: 4,
    categories: [ItemCategory.PICKAXE, ItemCategory.AXE, ItemCategory.SHOVEL, ItemCategory.HOE, ItemCategory.BOOK],
    conflicts: ["fortune"],
  },
  {
    id: "fortune",
    name: "Fortune",
    maxLevel: 3,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: [ItemCategory.PICKAXE, ItemCategory.AXE, ItemCategory.SHOVEL, ItemCategory.HOE, ItemCategory.BOOK],
    conflicts: ["silk_touch"],
  },
  {
    id: "power",
    name: "Power",
    maxLevel: 5,
    itemMultiplier: 1,
    bookMultiplier: 1,
    categories: [ItemCategory.BOW, ItemCategory.BOOK],
    conflicts: [],
  },
  {
    id: "punch",
    name: "Punch",
    maxLevel: 2,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: [ItemCategory.BOW, ItemCategory.BOOK],
    conflicts: [],
  },
  {
    id: "flame",
    name: "Flame",
    maxLevel: 1,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: [ItemCategory.BOW, ItemCategory.BOOK],
    conflicts: [],
  },
  {
    id: "infinity",
    name: "Infinity",
    maxLevel: 1,
    itemMultiplier: 8,
    bookMultiplier: 4,
    categories: [ItemCategory.BOW, ItemCategory.BOOK],
    conflicts: ["mending"],
  },
  {
    id: "piercing",
    name: "Piercing",
    maxLevel: 4,
    itemMultiplier: 1,
    bookMultiplier: 1,
    categories: [ItemCategory.CROSSBOW, ItemCategory.BOOK],
    conflicts: ["multishot"],
  },
  {
    id: "multishot",
    name: "Multishot",
    maxLevel: 1,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: [ItemCategory.CROSSBOW, ItemCategory.BOOK],
    conflicts: ["piercing"],
  },
  {
    id: "quick_charge",
    name: "Quick Charge",
    maxLevel: 3,
    itemMultiplier: 2,
    bookMultiplier: 1,
    categories: [ItemCategory.CROSSBOW, ItemCategory.BOOK],
    conflicts: [],
  },
  {
    id: "loyalty",
    name: "Loyalty",
    maxLevel: 3,
    itemMultiplier: 2,
    bookMultiplier: 1,
    categories: [ItemCategory.TRIDENT, ItemCategory.BOOK],
    conflicts: ["riptide"],
  },
  {
    id: "impaling",
    name: "Impaling",
    maxLevel: 5,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: [ItemCategory.TRIDENT, ItemCategory.BOOK],
    conflicts: [],
  },
  {
    id: "riptide",
    name: "Riptide",
    maxLevel: 3,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: [ItemCategory.TRIDENT, ItemCategory.BOOK],
    conflicts: ["loyalty", "channeling"],
  },
  {
    id: "channeling",
    name: "Channeling",
    maxLevel: 1,
    itemMultiplier: 8,
    bookMultiplier: 4,
    categories: [ItemCategory.TRIDENT, ItemCategory.BOOK],
    conflicts: ["riptide"],
  },
  {
    id: "luck_of_the_sea",
    name: "Luck of the Sea",
    maxLevel: 3,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: [ItemCategory.FISHING_ROD, ItemCategory.BOOK],
    conflicts: [],
  },
  {
    id: "lure",
    name: "Lure",
    maxLevel: 3,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: [ItemCategory.FISHING_ROD, ItemCategory.BOOK],
    conflicts: [],
  },
  {
    id: "density",
    name: "Density",
    maxLevel: 5,
    itemMultiplier: 2,
    bookMultiplier: 1,
    categories: [ItemCategory.MACE, ItemCategory.BOOK],
    conflicts: ["sharpness", "smite", "bane_of_arthropods", "breach"],
  },
  {
    id: "breach",
    name: "Breach",
    maxLevel: 4,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: [ItemCategory.MACE, ItemCategory.BOOK],
    conflicts: ["sharpness", "smite", "bane_of_arthropods", "density"],
  },
  {
    id: "wind_burst",
    name: "Wind Burst",
    maxLevel: 3,
    itemMultiplier: 4,
    bookMultiplier: 2,
    categories: [ItemCategory.MACE, ItemCategory.BOOK],
    conflicts: [],
  }
];
